### ISSUE TITLE
How you find the reduction cell?

### ISSUE THREAD

**Issue by Catosine** [D-X-Y/GDAS#6]
Hello,

I'm kind of interested in how you decide the fixed reduction cell. Do you test different reduction cells? How are the performances of those cells?

Thank you!

**Comment by D-X-Y** [comment]
Thanks for your interest. 
It is a little bit heuristic. Since directly applying MaxPool2d with stride = 2 will lose some information, we hope to add another branch ``https://github.com/D-X-Y/GDAS/blob/master/lib/nas/construct_utils.py#L114`` to complement the MaxPool operation. Using 1x3 with 3x1 conv is to reduce the complexity of 3x3 convolution, which is also introduced in GoogleNet.

We also tried several other manually designed reduction cells, while this one gives the best performance on CIFAR.
